pipeline:
  name: pipe_ff_v2LJmrz
  identifier: pipe_ff_v2LJmrz
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: Desc Added
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: t1
                  identifier: t1
                  template:
                    templateRef: step_ff_allverajcgT
                    versionLabel: v2
                    templateInputs:
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
        tags: {}