pipeline:
  name: opa_connector_blocked_idvvY
  identifier: opa_connector_blocked_idvvY
  orgIdentifier: Simlified_Git_sync
  projectIdentifier: opa_gitx_proj_8b8nO
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsc
                  identifier: dsc
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}